### ISSUE TITLE
512-bit vectorized SIMD reduce add and 512-bit popcount must be re-added

### ISSUE THREAD

**Issue by vadixidav** [rust-cv/bitarray#1]
Originally, it was found that certain Intel instructions that lead to enhanced performance could only be generated (to my knowledge) using LLVM intrinsics `llvm.experimental.vector.reduce.add.v4i128` and `llvm.ctpop.v4i128`. These were added internally to `bitarray`, but @codec-abc discovered a bug with this on his installation of Rust where LLVM did not consider the passed type to be correct for the intrinsic. To fix this, this was removed.

This could be a performance concern to Rust CV, since the initial two-view brute force match between binary features runs these operations in a tight loop to determine the optimal nearest neighbor in hamming space. However, this will be mitigated with better approaches than brute-force. Nonetheless, it does overall slow down matching, even using Bag of Words (BoW), proportionally to how quickly this routine can be executed. At some point we will need to investigate how we can have the right instructions generated, perhaps through auto-vectorization rather than LLVM intrinsics. If Rust gains the ability to perform these instructions natively (through `core::arch`), then we will be able to fix this easily.

**Comment by vadixidav** [comment]
@killzoner You mentioned in #2 that you might contribute a change to optionally enable this capability. Have you started on that? If not, I might be able to work on this during the weekend.

**Comment by vadixidav** [comment]
I have started working on this.

**Comment by vadixidav** [comment]
The new feature `unstable-512-bit-simd` is added which allows one to enable this functionality once again.

**Comment by killzoner** [comment]
Sorry @vadixidav I was away from any computer for the last 10 days, so I didn't get the chance to get my hands on it. Thank you so much for having this done in the meantime 🙇
