### ISSUE TITLE
Performance regression in 0.2.5

### ISSUE THREAD

**Issue by killzoner** [rust-cv/bitarray#2]
Hi @vadixidav,

Sorry for the late notification, I recently made an update of `bitarray` from 0.2.3 to 0.2.5 and noticed a pretty big performance issue.
I have a test in my project (which is pretty much https://github.com/rust-cv/cv/blob/5e4754050bef9d884f8c234072044febfb9a8791/akaze/tests/estimate_pose.rs with a timer) that I run from time to time to check for performance regressions/enhancement when upgrading.
It's around 200ms difference, but for my project since I do akaze matching in parallel, it ends up with around 2s more (about twice the nominal time).

I confirmed it's related to 0.2.5, and looking at the commits, I saw that this is most probably due to "512-bit SIMD intrinsic" removal. Can you provide some background on it, and is there any future plan regarding this?

If you're willing to keep it I could work on specific feature flag for this.

Thanks!

**Comment by vadixidav** [comment]
@killzoner Yes, we could add in a feature flag to preserve this. However, we need to be careful to avoid breaking the code on computers that don't support it. Some people were reporting issues with the LLVM intrinsics on their computers (we don't know what causes the issue).

This change is entirely internal, so feel free to create a PR for this. We can have @codec-abc test that it continues to work without the flag, as they have encountered issues building with this in the code. The feature should be disabled by default. You can name it whatever you want, so long as it refers to llvm intrinsics.

One alternative that might solve this without the intrinsics is if you can somehow get the autovectorizor to generate the same code as using the LLVM intrinsics does, but I was unable to do that after trying for several hours in godbolt. I would recommend just adding the intrinsics back in behind a feature gate.

Also, thank you for letting me know about this issue. I was aware of the regression, but I did not know exactly what effects would occur by changing that. Feel free to reach out if you have additional issues, and I would love to get a PR for this feature.

**Comment by vadixidav** [comment]
@killzoner Hey, I am going to close this issue in favor of #1, as that was created to track this problem.

**Comment by vadixidav** [comment]
@killzoner Just wanted to let you know that the feature `unstable-512-bit-simd` was added and published in version `0.2.6` as part of issue #1.

**Comment by killzoner** [comment]
@vadixidav just saw that, thanks. I will take a look at 0.2.6. Out of curiosity, is there any alternative approach to brute force matching with rust-cv ecosystem?

**Comment by killzoner** [comment]
Also I noticed that plans for rust 1.47 include an upgrade to llvm 11, I will have a look at the features to see if it brings anything new regarding this
